# Generated by Django 2.0 on 2017-12-27 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buysell', '0008_auto_20171227_1434'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductType',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('exchange', 'Exchange')], max_length=20, unique=True, verbose_name='Select purpose of product'),
        ),
    ]
