# Generated by Django 2.0 on 2017-12-27 10:47

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('buysell', '0009_auto_20171227_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('exchange', 'Exchange')], max_length=17, verbose_name='Select purpose of product'),
        ),
    ]
